[package]
name = "rsnek_ast"
version = "0.0.1"
authors = ["Dillon Hicks <dillon@dillonhicks.io>"]

[lib]
name = "rsnek_ast"

[features]
const_fn = []

[dependencies]
rsnek_proc_macros =  { version = "*", path = "../rsnek_proc_macros" }
num = "*"
itertools = "*"

