version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing rust nightly toolchain
      - make toolchain
  build:
    commands:
      - echo Build started on `date`
      - make build
      - echo Test started on `date`
      - make test
      - echo Bench started on `date`
      - make bench
      - echo Release started on `date`
      - make release
post_build:
    commands:
      - echo Docs started on `date`
      - make docs
      - echo Finshed on `date`
artifacts:
    files:
      - 'docs/*'
      - 'release/rsnek'
    base-directory: 'target'
