version: 0.1

phases:
  pre_build:
    commands:
      - echo Install Toolchain started on `date`
      - echo Installing rust nightly toolchain
      - make toolchain
  build:
    commands:
      - echo Build started on `date`
      - make build
      - echo Test started on `date`
      - make test
      - echo Bench started on `date`
      - make bench
      - echo Perf started on `date`
      - make perf
      - echo Release started on `date`
      - make release
      - echo Test Release started on `date`
      - make test-release
      - echo Docs started on `date`
      - make docs
      - echo Finshed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'target'
  discard-paths: no
