[package]
name = "rattlesnake"
version = "0.1.0"
authors = ["Dillon Hicks <dillon@blinkhealth.com>"]


[lib]
name = "rattlesnake"


[dependencies]
num = "0.1"


[features]

rsnek-debug-heap = []
rsnek-debug = []