[package]
name = "rattlesnake"
version = "0.1.0"
authors = ["Dillon Hicks <dillon@dillonhicks.io>"]


[lib]
name = "rattlesnake"


[dependencies.fringe]
version = "1.2.1"

[dependencies]
num = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"

[features]
rsnek-debug-heap = []
rsnek-debug = []