[package]
name = "rsnek_compile"
version = "0.0.1"
authors = ["Dillon Hicks <dillon@dillonhicks.io>"]

include = [
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[lib]
name = "rsnek_compile"

[features]
const_fn = []

[dependencies]
rsnek_proc_macros =  { version = "*", path = "../rsnek_proc_macros" }
num = "*"
itertools = "*"
serde = "*"
serde_yaml = "*"
serde_json = "*"
serde_derive = "*"
serde_bytes = "*"
serde-pickle = "*"
bincode = "*"


bytes = {git = "https://github.com/carllerche/bytes", rev = "ec7d7f27fe04ca220caafd6691b06690cca7b698" }

[dependencies.nom]
version = "^2.2"
features = ["regexp", "regexp_macros", "verbose-errors"]
