[package]
name = "rsnek_runtime"
version = "0.2.0"
authors = ["Dillon Hicks <dillon@dillonhicks.io>"]

[lib]
name = "rsnek_runtime"

[dependencies.fringe]
version = "1.2.1"

[dependencies]
num = "*"
itertools = "*"
