[package]
name = "rsnek_runtime"
version = "0.2.0"
authors = ["Dillon Hicks <dillon@dillonhicks.io>"]

[lib]
name = "rsnek_runtime"

[features]
fn_traits = []

[dependencies]
num = "*"
itertools = "*"
fringe = "*"

serde = "*"
serde_derive = "*"

rsnek_compile = {path = "../rsnek_compile" }
