[package]
name = "rsnek"
version = "0.0.1"
authors = ["Dillon Hicks <dillon@dillonhicks.io>"]
build = "build.rs"

[dependencies]
log4rs = "^0.6.3"
log = "^0.3.7"

clap = "*"
rsnek_runtime =  { version = "*", path = "../rsnek_runtime" }
rsnek_compile = { version = "*", path = "../rsnek_compile" }

[build-dependencies]
rustc_version = "*"